# Generated by Django 5.1.5 on 2025-01-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MANHWA", "Manhwa"),
                            ("MANGA", "Manga"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(upload_to="item_images/")),
                ("rating", models.IntegerField(help_text="Rating out of 10")),
                ("review", models.TextField()),
            ],
        ),
    ]
