# Generated by Django 5.1.5 on 2025-01-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga_log_app", "0003_alter_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="item_images/"),
        ),
    ]
